package ayudaencasa.workers.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


import java.io.Serializable;
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "worker")
public class Worker implements Serializable {
    @DynamoDBHashKey (attributeName = "uId")
    private String uId;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private String profession;
    @DynamoDBAttribute
    private String mail;
    @DynamoDBAttribute
    private String mailAlt;
    @DynamoDBAttribute
    private int telephone;
    @DynamoDBAttribute
    private float length;
    @DynamoDBAttribute
    private float latitude;

    public String getuId() {
        return uId;
    }

    public void setuId(String uId) {
        this.uId = uId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getProfession() {
        return profession;
    }

    public void setProfession(String profession) {
        this.profession = profession;
    }

    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getMailAlt() {
        return mailAlt;
    }

    public void setMailAlt(String mailAlt) {
        this.mailAlt = mailAlt;
    }

    public int getTelephone() {
        return telephone;
    }

    public void setTelephone(int telephone) {
        this.telephone = telephone;
    }

    public float getLength() {
        return length;
    }

    public void setLength(float length) {
        this.length = length;
    }

    public float getLatitude() {
        return latitude;
    }

    public void setLatitude(float latitude) {
        this.latitude = latitude;
    }
}
